# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Config map holds the boot.json for this instance.
# This is now *DEPRECATED*. The boot.json file is now created by the init container. This is here for
# sample purposes, and will be removed in the future.
apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-json
data:
  boot.json: |
   {
     "instance" : "{{ default "http://openam:80/openam" .Values.openamInstance }}",
     "dsameUser" : "cn=dsameuser,ou=DSAME Users,{{ .Values.rootSuffix }}",
     "keystores" : {
       "default" : {
         "keyStorePasswordFile" : "{{ .Values.openamHome }}/openam/.storepass",
         "keyPasswordFile" : "{{ .Values.openamHome }}/openam/.keypass",
         "keyStoreType" : "JCEKS",
         "keyStoreFile" : "{{ .Values.openamHome }}/openam/keystore.jceks"
       }
     },
     "configStoreList" : [ {
       "baseDN" : "{{.Values.rootSuffix }}",
       "dirManagerDN" : "cn=Directory Manager",
       "ldapHost" : "{{ default "opendj-configstore-0.opendj-configstore" .Values.configLdapHost }}",
       "ldapPort" : {{ default 1389 .Values.configLdapPort }},
       "ldapProtocol" : "ldap"
     } ]
   }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: am-configmap
data:
  DOMAIN: "{{ .Values.global.domain }}"
  CATALINA_OPTS: "{{ .Values.catalinaOpts }}"
  GIT_REPO: "{{ .Values.global.git.repo }}"
  GIT_CHECKOUT_BRANCH: "{{ .Values.global.git.branch }}"
  GIT_ROOT:  "/git"
  GIT_PROJECT_DIRECTORY: "{{ .Values.global.git.projectDirectory }}"
  GIT_SSH_COMMAND: "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /etc/git-secret/ssh"
  GIT_AUTOSAVE_BRANCH:  autosave-am-{{ .Release.Namespace }}
  CONFIG_PATH: "{{ .Values.global.configPath.am }}"
  {{ if .Values.amCustomizationScriptPath -}}
  CUSTOMIZE_AM: "/git/{{.Values.global.git.projectDirectory }}/{{ .Values.global.configPath.am }}/{{ .Values.amCustomizationScriptPath }}"
  {{- end }}
