# Copyright (c) 2016-2017 ForgeRock AS.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openam
spec:
  replicas: {{default 1 .Values.openamReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: openam
        vendor: forgerock
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: git-init
        image: {{ template "gitImage" . }}
        imagePullPolicy:  {{ template "pullPolicy" . }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name: am-configmap
      containers:
      - name: openam
        image: {{ template "image" . }}
        imagePullPolicy:  {{ template "pullPolicy" . }}
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: openam-root
          mountPath: /home/forgerock/openam
        - name: git
          mountPath: /git
        {{ if .Values.createBootstrap -}}
        - name: configstore-secret
          mountPath: /var/run/secrets/configstore
        - name: openam-secrets
          mountPath: /var/run/secrets/openam
        - name: openam-boot
          mountPath: /var/run/openam
        {{ else }}
        args: [ "run-nowait" ]
        {{- end }}
        envFrom:
        - configMapRef:
            name: am-configmap
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # For slow environments like Minikube you need to give OpenAM time to come up.
        readinessProbe:
          httpGet:
            path: /openam/isAlive.jsp
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /openam/isAlive.jsp
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: {{ .Values.livenessTimeout }}
          periodSeconds: {{ .Values.livenessPeriod }}
      volumes:
      - name: openam-root
        emptyDir: {}
      - name: openam-secrets
        secret:
          secretName: openam-secrets
      - name: openam-boot
        configMap:
          name: boot-json
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName: git-am-{{ .Release.Name }}
          # The forgerock user needs read access to this secret
          #defaultMode: 256
      {{ if .Values.createBootstrap -}}
      - name: configstore-secret
        secret:
          secretName: configstore
          #defaultMode: 256
      {{- end }}