apiVersion: v1
kind: Pod
metadata:
  name: amster
spec:
  containers:
    - image: amster:fullstack
      imagePullPolicy: IfNotPresent
      name: amster
      env:
      - name: IDP_FACEBOOK_CLIENTID
        valueFrom:
          secretKeyRef:
            name: social-credentials
            key: IDP_FACEBOOK_CLIENTID
      - name: IDP_FACEBOOK_CLIENTSECRET
        valueFrom:
          secretKeyRef:
            name: social-credentials
            key: IDP_FACEBOOK_CLIENTSECRET
      - name: OPENAM_INSTANCE
        value: "http://am-service.sample.svc.cluster.local"
      resources:
          requests:
            memory: "256Mi"
