apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dj
spec:
  serviceName: dj-service
  replicas: 1
  template:
    metadata:
      labels:
        role: persistence
    spec:
      containers:
        - image: dj:fullstack
          imagePullPolicy: IfNotPresent
          name: opendj
          env:
          - name: BASE_DN
            value: "dc=example,dc=com"
          - name: DJ_MASTER_SERVER
            value: dj-0.dj-service
          ports:
            - containerPort: 1389
              name: ldap
              protocol: TCP
            - containerPort: 4444
              name: djadmin
              protocol: TCP
          resources:
              requests:
                memory: "512Mi"
          readinessProbe:
            exec:
              command: ["/opt/opendj/probe.sh"]
            periodSeconds: 20
            initialDelaySeconds: 30
          livenessProbe:
            exec:
              command: ["/opt/opendj/probe.sh"]
            initialDelaySeconds: 300
            periodSeconds: 60
