apiVersion: v1
kind: Pod
metadata:
  name: idm
  labels:
    role: management
spec:
  initContainers:
  - name: wait-for-repo
    image: "groundnuty/k8s-wait-for:0.3"
    imagePullPolicy: IfNotPresent
    args: [ "pod", "-l", "role=persistence" ]
  containers:
    - image: idm:fullstack
      imagePullPolicy: IfNotPresent
      name: openidm
      env:
      - name: OPENIDM_CLUSTER_REMOVE_OFFLINE_NODE_STATE
        value: "true"
      - name: OPENIDM_CONFIG_REPO_ENABLED
        value: "false"
      - name: IDP_FACEBOOK_CLIENTID
        valueFrom:
          secretKeyRef:
            name: social-credentials
            key: IDP_FACEBOOK_CLIENTID
      - name: IDP_FACEBOOK_CLIENTSECRET
        valueFrom:
          secretKeyRef:
            name: social-credentials
            key: IDP_FACEBOOK_CLIENTSECRET
      - name: OPENIDM_ANONYMOUS_PASSWORD
        value: "anonymous"
      - name: OPENIDM_ADMIN_PASSWORD
        value: "openidm-admin"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
          requests:
            memory: "512Mi"
