# This grants cluster admin (root like privileges) to the default service account.
# This is a quick and dirty way of enabling RBAC for the kube-dns and nginx ingress add-ons.
# To do this properly, the addons should have service accounts and the proper roles assigned.
# Track: https://github.com/kubernetes/minikube/issues/1722  (minikube - Enable RBAC by default)
# Another way of doing this:
# kubectl create clusterrolebinding fixRBAC --clusterrole=cluster-admin --serviceaccount=kube-system:default
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fixRBAC
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system