# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
apiVersion: v1
kind: Service
metadata:
  name: {{ template "instanceName" . }}
  labels:
    app: {{ template "instanceName" . }}
    component: opendj
    vendor: forgerock
spec:
  clusterIP: None
  ports:
    - port: 1389
      name: ldap
      targetPort: 1389
    - port: 4444
      name: djadmin
      targetPort: 4444
  selector:
    djInstance: {{ template "instanceName" . }}