# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  # If you want to run more than one IG deployment in the same namespace, change the deployment name 
  # below to the {{ template "fullname" . }} to make the name unique.
  name: openig
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.component }}
    spec:
      initContainers:
      - name: git-init
        image: {{ template "gitImage" . }}
        imagePullPolicy:  {{ template "pullPolicy" . }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ template "fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ template "pullPolicy" . }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
# todo: Create a health check URL
#        livenessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#          timeoutSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#          initialDelaySeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName:  {{ template "fullname" . }}
          # The forgerock user needs to be able to read this file.
          #defaultMode: 256
