# Note that secret values are base64-encoded.
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "fullname" . }}
type: Opaque
data:
  # The *private* ssh key used to perform authenticated git pull or push.
  # The default value is a dummy key that does nothing
  ssh:  {{ default "dGhpcyBpcyBhIGR1bW15IGtleQo=" .Values.global.git.sshKey }}