# Default values for openam runtime chart
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into the templates.

component: openam

global:
  domain: .example.com
  image:
    repository: forgerock
    tag: 5.5.0
    pullPolicy: IfNotPresent
  git:
    # git repo to clone. The value below is a public git repo that does not require authentication.
    repo: "https://stash.forgerock.org/scm/cloud/forgeops-init.git"
    branch: release/5.5.0
    projectDirectory: "forgeops-init"
  configPath:
    am: default/am/empty-import
  exportPath:
      am: default/am/autosave
  # If you set this to true, you must have a TLS secret with the same name as the FQDN.
  useTLS: false

openamReplicaCount: 1

openamInstance: http://openam:80/openam

configLdapPort:  1389
configLdapHost: configstore-0.configstore


catalinaOpts: >
  -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'

# For visualVM debug, you can add this to the above:
#-Dcom.sun.management.jmxremote.port=<port>
#-Dcom.sun.management.jmxremote.authenticate=false
#-Dcom.sun.management.jmxremote.ssl=false
#-Dcom.sun.management.jmxremote.rmi.port=<port>
#-Djava.rmi.server.hostname=$HOST_HOSTNAME

# Suffix for OpenDJ config store.
rootSuffix:  "dc=openam,dc=forgerock,dc=org"

# Valid logger types: fluent-bit, none
# For audit logs it is suggested you configure AM to send directly to ElasticSearch.
logDriver: none

# The defaults below are small and OK for testing.
# For production you wil want to set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 1300Mi
 requests:
   memory: 1200Mi


openamHome: /home/forgerock/openam

# Set to true to create a boot.json file to bootstrap AM. If set to false, AM will come up to the configurator page.
createBootstrap: true

# This is an optional path to a script to execute before AM starts up. It can copy in images, update the web.xml, etc.
# The path is *relative* to /git/{{ projectDirectory }}/{{ configPath.am }}.
# For example:   /git/forgeops-init/default/am/my-config/customize-am.sh
amCustomizationScriptPath: "customize-am.sh"

# Liveness probe tuning - time in seconds
livenessPeriod: 60
livenessTimeout: 15