# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
#
# Default values for OpenIG.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1


global:
  domain: .example.com
  image:
    repository: forgerock
    tag: 5.5.0
    pullPolicy: IfNotPresent
  git:
    # git repo to clone. The value below is a public git repo that does not require authentication.
    repo: "https://stash.forgerock.org/scm/cloud/forgeops-init.git"
    branch: release/5.5.0
    projectDirectory: forgeops-init
  configPath:
    ig: default/ig/basic-sample
  # If you set this to true, you must have a TLS secret with the same name as the FQDN
  useTLS: false

service:
  name: openig
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

resources:
#  limits:
#    cpu: 1000m
#    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi


# These are both used to form the FQDN for the load balancer.  See _helpers.tpl
component: openig

