# Sample value overrides for Helm. The values below will work out of the box, and
# are the same as the default values.yaml in the charts.
# To override these values, make a copy of this file, and pass it to helm with the -f option
# Example:  helm install -f my-custom.yaml openam
# *DO NOT* check your custom.values file into git, as it may contain ssh credentials. See below


# Global variables are used in all charts, including child charts nested under a parent chart.
# Refer to https://github.com/kubernetes/helm/blob/master/docs/charts.md#scope-dependencies-and-values for more information
# Be careful of proper yaml nesting here.
global:
  image:
    # Image repo and tag. The image that is pulled will be  {repository}/{component}:{tag}
    # Example:  set repository: quay.io/acme, tag: 1.0.1, the openam image formed is: quay.io/acme/openam:1.0.1
    repository: forgerock
    tag: 5.5.0
    # If you want to force a re-pull of all images set this to "Always"
    pullPolicy: IfNotPresent
  # The domain - including a leading dot '.'.  Product FQDNs are formed using this domain.
  # The format is  {component}.{kube-namespace}.{domain}.  For example: openam.default.example.com
  domain: .example.com
  # As an alternative to using fake domain names in /etc/hosts, you can use xip.io and your minikube IP address:
  # domain: .192.168.99.100.xip.io
  # Git Configuration:
  # Where to pull product configuration, or push it (pushing requires git ssh credentials)
  git:
    # git repo to clone. The value below is a public git repo that does not require authentication.
    repo: "https://stash.forgerock.org/scm/cloud/forgeops-init.git"
    projectDirectory: "forgeops-init"
    branch: release/5.5.0
    # This is a base64 encoded ssh private key for git authentication, required for pulling from
    # private git repos, or pushing to a git repo. The value below is not a real ssh key and will not work.
    # You need to replace this with your own ssh key. If you are just cloning http:// public repos that do not require
    # authentication, this variable can be ignored.  If you set your own ssh key, do not check this file into git
    # Generate a key using:
    # ssh-keygen -t rsa -C "forgeops-robot@forgeops.com" -f ssh.   Do not enter a passphrase!
    # Base64 encode the value using base64 <ssh
    # and enter below. The generated ssh.pub key is the public key to add to your stash or github repo
    # to allow access.
    sshKey:  dGhpcyBpcyBhIGR1bW15IGtleQo=
    # Optional sed filter to run after git checkout. The sed edit script here will be recursively run on *every*
    # file checked out to the /git directory. You must include the -e option to sed, and you can specify
    # multiple substitutions by repeating the -e s/// pattern. For example:
    # sedFilter: "-e s/openam.default.com/openam.test.com/ -e s/acme/foobar/"
    # Note that this will *not* change values in config maps. If you are changing the FQDN on install
    # make sure you also change global.domain above.
    sedFilter: ""
  # The relative path to the product configuration to import. Relative to /git/$projectDirectory/
  # specify the full path to the configuration
  configPath:
    idm:  default/idm/sync-with-ldap-bidirectional
    am:   default/am/empty-import
    ig:   default/ig/basic-sample
  # For AM only, you can specify a different export path. If this is not set, the export path defaults to  $configPath.am
  exportPath:
    am: default/am/autosave
  # Set this to true to use TLS for the ingresses for AM, IG, and IDM
  # If you set this to true, you must create the TLS secrets manually.
  # See bin/gen-ssl-secret.sh for an example of how to create a self-signed certificate.
  # Example command:   bin/gen-ssl-secret.sh openam.default.example.com
  # Will generate a self-signed certificate for the openam.default.example.com ingress.
  # The CN of the certificate *MUST* match the FQDN.
  useTLS: false
