# Default values for cmp-openidm-dj-postgres.


# Override any child variables

global:
  image:
    repository: gcr.io/engineering-devops
    tag: 5.5.0


# Default is to install userstore.  Run with helm install --set tags.userstore=false to override
# Note that the userstore might have been deployed with one of the AM samples as well.
tags:
  userstore: true

# Generate some sample users
opendj:
  numberSampleUsers: 100